/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/car.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('./models/car.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={51.57} position={[-0.02, 0.03, 0.03]} rotation={[-0.8, -0.44, -0.41]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={23.49} position={[-0.04, 0.02, 0.08]} rotation={[-0.29, -0.52, -0.15]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={38.96} position={[-0.01, 0.01, 0.03]} rotation={[-0.26, -0.59, -0.15]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={36.1} position={[-0.04, -0.01, 0.05]} rotation={[0.01, -0.68, 0]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={55} position={[-0.01, 0.01, -0.02]} rotation={[-2.79, -0.65, -2.92]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={55} position={[-0.04, 0.03, -0.05]} rotation={[-2.32, -0.55, -2.63]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={55} position={[0.01, 0.01, -0.02]} rotation={[-2.77, 0.67, 2.9]} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={55} position={[-0.01, 0.01, 0.01]} rotation={[-0.55, -0.55, -0.31]} />
      <mesh geometry={nodes.ToyCar.geometry} material={materials.ToyCar} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Fabric.geometry} material={materials.Fabric} rotation={[Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Glass.geometry} material={materials.Glass} rotation={[Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('./models/car.glb')
